### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by decentral1se** [oliver-moran/reusingcork#1]
Hi! Great that you are bringing the good initiative of ReusingDublin down to Cork. I'd love to know the status of the project? Is it solely the web portal right now? Where is the vacant location data? Is there a web API? Is there a mobile app for this?

**Comment by oliver-moran** [comment]
Luke, apologies! I didn't see your comment until just now.

The status of the project is exactly as you seen

**Is it solely the web portal right now?**
Essentially, yes. However, I have used the portal as an opportunity to highlight the issue of vacancy in local media.

**Where is the vacant location data?**
The data can be downloaded here: http://www.reusingcork.ie/api/data/export

Currently there are 124 locations added by the public. In addition, I have received a file containing many more via email and I plan to add these.

**Is there a web API?**
Yes. Everything that can be done on the website can be done using an API.

**Is there a mobile app for this?**
The website itself is mobile responsive and can be installed on a mobile phone using the "Add to home screen" functionality of Android/iOS.

That said, there are some tweaks that could be done to make integrate this better (e.g. a nicer icon, etc.). I might do this over the weekend.

**Comment by decentral1se** [comment]
Great, thanks for getting back to me @oliver-moran!
